project:
  type: website
  output-dir: docs

website:
  title: "Sarah Tanja's Open Lab Notebook"
  favicon: "images/favicon.png"
  page-navigation: true
  description: "This Open Lab Notebook is a creative landing space for learning about Bioinformatics, Marine Botany, & Data Science. It's mostly for me, but also for you! 😘"
  site-url: https://sarahtanja.github.io/quarto-blog/
  repo-url: https://github.com/sarahtanja/quarto-blog
  
  navbar:
    logo: "images/binocs.png"
    logo-alt: "Self-portrait at Tracy Arm, watercolor artwork by Sarah Tanja"
    background: primary
    foreground: light
    search: true
    right: #align navbar items to right/left/center
      - text: "About"
        file: about.qmd
      - text: "Projects"
        file: projects.qmd
      - icon: linkedin #bootstrap icon
        href: https://www.linkedin.com/in/sarah-tanja-595722146/
      - icon: github
        href: https://github.com/sarahtanja
      - icon: envelope-heart #bootstrap icon
        href: mailto:stanja@uw.edu
        
  
  page-footer: 
    left: "This page is built using [Quarto](https://quarto.org/)❤️" 

format:
  html:
    theme: 
      light: journal
      dark: solar
    css: styles.css
    page-layout: full
    code-background: true
    code-copy: true
    toc: true 

editor: visual

