{
  "hash": "8d471f620d6f9ab90d9f841783c83c6a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bench Incubation\"\nsubtitle: \"Lab bench records and environmental logs for the development of *Montipora capitata* embryos exposed to PVC leachate\"\ndate: 07/09/2024\ncategories: [protocols, records]\n---\n\n# Background\n\nOn July 5th, 6th, and 7th 2024 we conducted an ecotox assay on the development of *Montipora capitata* coral embryo development under exposure to PVC leachate at nominal concentrations of 0 mg/L (0.22um FSW, control), 0.01 mg/L (low), 0.1 mg/L (mid), and 1 mg/L (high). We repeated our assay across three nights of spawning. In the assay, embryos were incubated in 20mL scintillation vials in a climate-controlled lab. Here we detail the conditions of the incubation period.\n\nWe left a HOBO logger out on the lab bench, in the lab hood, and in an ambient flow through holding tank where adult coral colonies were being kept. We will compare the data here.\n\n## Inputs\n\n-   HOBO data logs\n\n## Outputs\n\n-   Visualizations comparing the lab bench conditions to the ambient seawater at HIMB around the July *Montipora capitata* spawning event in 2024.\n\n# Setup\n\n\n\n## Install packages\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nif (\"tidyverse\" %in% rownames(installed.packages()) == 'FALSE') install.packages('tidyverse')\nif (\"reshape2\" %in% rownames(installed.packages()) == 'FALSE') install.packages('reshape2')\nif (\"plotly\" %in% rownames(installed.packages()) == 'FALSE') install.packages('plotly')\nif (\"car\" %in% rownames(installed.packages()) == 'FALSE') install.packages('car')\nif (\"agricolae\" %in% rownames(installed.packages()) == 'FALSE') install.packages('agricolae')\nif (\"hms\" %in% rownames(installed.packages()) == 'FALSE') install.packages('hms')\n```\n:::\n\n\n## Load packages\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(reshape2)\nlibrary(plotly)\nlibrary(car) # for Levene's test \nlibrary(agricolae) # for post-hoc tests\nlibrary(hms)\n```\n:::\n\n\n## Load HOBO logs\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbench <- read.csv(\"embryo-inc-bench 2024-07-08 13_34_32 HST (Data HST).csv\")\nhood <- read.csv(\"embryo-inc-hood 2024-07-08 13_35_01 HST (Data HST).csv\")\ntank1 <- read.csv(\"Holding tank  2024-07-03 15_30_47 HST (Data HST).csv\")\ntank2 <- read.csv(\"Holding tank  2024-07-08 08_32_55 HST (Data HST).csv\")\ntank3 <- read.csv(\"AmbientTemp2 2024-07-08 08_32_20 HST (Data HST).csv\")\n```\n:::\n\n\n# Format HOBO logs \n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbench <- bench %>% \n  rename(datetime = Date.Time..HST.,\n         temp = Temperature.....C.,\n         lux = Light....lux.) %>%\n  mutate(location = \"bench\") %>% \n  select(datetime, temp, lux, location)\n\nhood <- hood %>% \n  rename(datetime = Date.Time..HST.,\n         temp = Temperature.....C.,\n         lux = Light....lux.) %>% \n  mutate(location = \"hood\") %>% \n  select(datetime, temp, lux, location)\n\ntank1 <- tank1 %>% \n  rename(datetime = Date.Time..HST.,\n         temp = Temperature.....C.,\n         lux = Light....lux.) %>% \n  mutate(location = \"tank1\") %>% \n  select(datetime, temp, lux, location)\n\ntank2 <- tank2 %>% \n  rename(datetime = Date.Time..HST.,\n         temp = Temperature.....C.,\n         lux = Light....lux.) %>% \n  mutate(location = \"tank2\") %>% \n  select(datetime, temp, lux, location)\n\ntank3 <- tank3 %>% \n  rename(datetime = Date.Time..HST.,\n         temp = Temperature.....C.,\n         lux = Light....lux.) %>% \n  mutate(location = \"tank3\") %>% \n  select(datetime, temp, lux, location)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nall <-  rbind(bench, hood, tank1, tank2, tank3)\n\nall$datetime <- as.POSIXct(all$datetime, format = \"%m/%d/%Y %H:%M:%S\")\n```\n:::\n\n\n# Plot overlapping logs\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlong <- melt(all, id.vars=c(\"datetime\", \"location\"), measure.vars=c(\"temp\", \"lux\"))\n```\n:::\n\n\nThe incubation windows were:\n\n1- July 5th 21:20 - July 6th 13:30\n\n2 - July 6th 21:20 - July 7th 13:30\n\n3- July 7th 21:20 - July 8th 13:30\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nincubation_windows <- data.frame(\n  start = as.POSIXct(c(\"07/05/2024 21:20:00\", \n                       \"07/06/2024 21:20:00\", \n                       \"07/07/2024 21:20:00\"), \n                     format = \"%m/%d/%Y %H:%M:%S\"),\n  end = as.POSIXct(c(\"07/06/2024 13:30:00\", \n                     \"07/07/2024 13:30:00\", \n                     \"07/08/2024 13:30:00\"), \n                   format = \"%m/%d/%Y %H:%M:%S\"))\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calculate scaling factor for the secondary (lux) axis\nlux_scale <- max(all$temp, na.rm = TRUE) / max(all$lux, na.rm = TRUE)\n\nggplot(all, aes(x = datetime)) +\n  # Highlight windows\n  geom_rect(\n    data = incubation_windows,\n    aes(xmin = start, xmax = end),\n    ymin = -Inf, ymax = Inf, fill = \"yellow\", alpha = 0.2, inherit.aes = FALSE\n  ) +\n  # Plot temp\n  geom_line(aes(y = temp, color = location), size = 1, alpha = 0.5) +\n  # Plot scaled lux\n  geom_line(aes(y = lux * lux_scale, color = location), linetype = \"dashed\") +\n  # Dual y-axis\n  scale_y_continuous(\n    name = \"Temperature\",\n    sec.axis = sec_axis(~ . / lux_scale, name = \"Lux\")\n  ) +\n  theme_minimal() +\n  labs(color = \"Location\", title = \"Temperature and Lux by Datetime with Incubation Highlights\")\n```\n\n::: {.cell-output-display}\n![](bench-incubation_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=7200}\n:::\n:::\n\n\n::: callout-caution\ntank2 and tank3 look like they had heaters in them that kept the min temp up near 26F...\n\nTO DO:\n\n-   go back and find HOBO log or sea surface temp from July 5th - 8th 2024.\n\n-   find calibration to convert lux to PAR\n:::\n\n# Averages\n\nWhat were the average bench, hood, and tank temps & light measurements across the incubation periods?\n\nSubset to the incubation windows\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nall_incubation <- all %>% \n    filter(\n    sapply(datetime, function(x) any(x >= incubation_windows$start & x <= incubation_windows$end))\n  )\n```\n:::\n\n\nDisplay a table of averages and standard deviations\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\navg_sd <- all_incubation %>%\n  filter(location %in% c(\"bench\", \"hood\" ,\"tank2\", \"tank3\")) %>%\n  group_by(location) %>%\n  summarize(\n    avg_temp = mean(temp, na.rm = TRUE),\n    sd_temp = sd(temp, na.rm = TRUE), \n    avg_lux = mean(lux, na.rm = TRUE),\n    sd_lux = sd(lux, na.rm = TRUE))\n\navg_sd\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|location | avg_temp|   sd_temp|    avg_lux|    sd_lux|\n|:--------|--------:|---------:|----------:|---------:|\n|bench    | 26.88575| 0.3975264|  243.58796|  495.4855|\n|hood     | 26.85602| 0.3655191|   91.64201|  140.3716|\n|tank2    | 26.37685| 0.3216703| 2498.80348| 5168.1143|\n|tank3    | 26.33780| 0.3106606| 2300.97458| 5338.2473|\n\n</div>\n:::\n:::\n\n\nPlot average temps\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(avg_sd, aes(x = location, y = avg_temp, color = location)) +\n  geom_point(size = 3) +                                           # mean temps as points\n  geom_errorbar(aes(ymin = avg_temp - sd_temp, ymax = avg_temp + sd_temp), width = 0.2) +  # std dev error bars\n  labs(x = \"Location\", y = \"Temperature (°C)\", title = \"Average Temperature with Standard Deviation\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](bench-incubation_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=7200}\n:::\n:::\n\n\nPlot average lux\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(avg_sd, aes(x = location, y = avg_lux, color = location)) +\n  geom_point(size = 3) +                                           # mean temps as points\n  geom_errorbar(aes(ymin = avg_lux - sd_lux, ymax = avg_lux + sd_lux), width = 0.2) +  # std dev error bars\n  labs(x = \"Location\", y = \"Lux\", title = \"Average lux with Standard Deviation\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](bench-incubation_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' width=7200}\n:::\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nall_incubation <- all_incubation %>% \n  mutate(\n    space = case_when(\n      location %in% c(\"bench\", \"hood\") ~ \"lab\",\n      location %in% c(\"tank2\", \"tank3\") ~ \"ambient\",\n      TRUE ~ NA_character_  # for any other location values\n    )\n  )\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\navg_sd <- all_incubation %>%\n  filter(space %in% c(\"lab\", \"ambient\")) %>%\n  group_by(space) %>%\n  summarize(\n    avg_temp = mean(temp, na.rm = TRUE),\n    sd_temp = sd(temp, na.rm = TRUE),\n    min_temp = min(temp, na.rm = TRUE),\n    max_temp = max(temp, na.rm = TRUE),\n    avg_lux = mean(lux, na.rm = TRUE),\n    sd_lux = sd(lux, na.rm = TRUE),\n    min_lux = min (lux, na.rm=TRUE),\n    max_lux = max(lux, na.rm=TRUE))\n\navg_sd\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|space   | avg_temp|   sd_temp| min_temp| max_temp|  avg_lux|    sd_lux| min_lux|  max_lux|\n|:-------|--------:|---------:|--------:|--------:|--------:|---------:|-------:|--------:|\n|ambient | 26.34765| 0.3134719|    25.95|    27.37| 2350.852| 5289.2776|       0| 31733.76|\n|lab     | 26.87088| 0.3818228|    25.91|    27.84|  167.615|  371.6999|       0|  8069.12|\n\n</div>\n:::\n:::\n\n\n\n::: callout-caution\nThe incubation temperature conditions were:\n\n- ambient 26.34 +/- 0.31 C (min 25.95, max 27.37)\n- lab 26.87 +/- 0.38 C (min 25.91, max 27.84) \n\nThe incubation lux conditions were:\n\n- ambient 2350.85 +/- 5289.27 lux (min 0, max 31733.76)\n- lab 167.61 +/- 371.69 lux (min 0, max 8069.12)\n:::\n\n# Hyopthesis testing\n\n## Is temp different across location?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Check homogeneity of variance\nleveneTest(temp ~ location, data = all_incubation)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      |  Df|  F value|    Pr(>F)|\n|:-----|---:|--------:|---------:|\n|group |   3| 4.863347| 0.0023137|\n|      | 937|       NA|        NA|\n\n</div>\n:::\n:::\n\n::: callout-caution\nOur data has unequal variances (Levene's test pvalue = 0.002314) so we use Welch's t-test for ANOVA\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Welch's ANOVA comparing temperature by stage\nwelch_anova <- oneway.test(temp ~ location, data = all_incubation, var.equal = FALSE)\nprint(welch_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne-way analysis of means (not assuming equal variances)\n\ndata:  temp and location\nF = 173.52, num df = 3.00, denom df = 351.78, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\nFollow up the Welch's t-test with a post-hoc test\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npairwise_results <- pairwise.t.test(\n  x = all_incubation$temp,\n  g = all_incubation$location,\n  p.adjust.method = \"bonferroni\",\n  pool.sd = FALSE\n)\nprint(pairwise_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using t tests with non-pooled SD \n\ndata:  all_incubation$temp and all_incubation$location \n\n      bench  hood   tank2\nhood  1      -      -    \ntank2 <2e-16 <2e-16 -    \ntank3 <2e-16 <2e-16 1    \n\nP value adjustment method: bonferroni \n```\n\n\n:::\n:::\n\n\n\n::: callout-caution\nPairwise comparisons of temperature across locations using Welch’s t-tests with Bonferroni-adjusted p-values revealed no significant difference between bench and hood (p = 1) or between tank2 and tank3 (p = 1). There is a significant difference (p<0.001) between the lab spaces (the bench and the hood) and the ambient spaces (The lab spaces are significantly different from the ambient spaces (tank2 and tank3). \n:::\n\n## Is temp different across space?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Check homogeneity of variance\nleveneTest(temp ~ space, data = all_incubation)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      |  Df|  F value|    Pr(>F)|\n|:-----|---:|--------:|---------:|\n|group |   1| 13.12683| 0.0003067|\n|      | 939|       NA|        NA|\n\n</div>\n:::\n:::\n\n\n::: callout-caution\nOur data has unequal variances so we use Welch's t-test for ANOVA\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Welch's ANOVA comparing temperature by stage\nwelch_anova <- oneway.test(temp ~ space, data = all_incubation, var.equal = FALSE)\nprint(welch_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne-way analysis of means (not assuming equal variances)\n\ndata:  temp and space\nF = 520.18, num df = 1.00, denom df = 852.66, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\nFollow up the Welch's t-test with a post-hoc test\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npairwise_results <- pairwise.t.test(\n  x = all_incubation$temp,\n  g = all_incubation$space,\n  p.adjust.method = \"bonferroni\",\n  pool.sd = FALSE\n)\nprint(pairwise_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using t tests with non-pooled SD \n\ndata:  all_incubation$temp and all_incubation$space \n\n    ambient\nlab <2e-16 \n\nP value adjustment method: bonferroni \n```\n\n\n:::\n:::\n\n\n## Is lab temp different across stage?\n\nAdd a column that indicates the duration of exposure by stage\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nall_incubation <- all_incubation %>%\n  mutate(\n    time_only = format(datetime, \"%H:%M:%S\"),      # extract time as string\n    time_only = hms::as_hms(time_only),            # convert to hms object for easier comparison\n    stage = case_when(\n      (time_only >= as_hms(\"21:20:00\") | time_only <= as_hms(\"03:30:00\")) ~ \"cleavage\",                         # crosses midnight\n      (time_only > as_hms(\"03:30:00\") & time_only <= as_hms(\"08:30:00\")) ~ \"prawnchip\",                          # normal range\n      (time_only > as_hms(\"08:30:00\") & time_only <= as_hms(\"13:30:00\")) ~ \"early gastrula\",                     # normal range\n      TRUE ~ NA_character_\n    )\n  )\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nbench_by_stage <- all_incubation %>%\n  filter(!is.na(stage)) %>% # remove rows where stage is missing\n  filter(space == \"lab\") %>% \n  group_by(stage) %>%\n  summarize(\n    avg_temp = mean(temp, na.rm = TRUE),\n    sd_temp = sd(temp, na.rm = TRUE),\n    min_temp = min(temp, na.rm = TRUE),\n    max_temp = max(temp, na.rm = TRUE),\n    avg_lux = mean(lux, na.rm = TRUE),\n    sd_lux = sd(lux, na.rm = TRUE),\n    min_lux = min(lux, na.rm = TRUE),\n    max_lux = max(lux, na.rm = TRUE)\n  )\n\nbench_by_stage\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|stage          | avg_temp|   sd_temp| min_temp| max_temp|  avg_lux|   sd_lux| min_lux| max_lux|\n|:--------------|--------:|---------:|--------:|--------:|--------:|--------:|-------:|-------:|\n|cleavage       | 26.87434| 0.2328657|    26.08|    27.24| 151.7127| 161.3920|    0.00|  409.28|\n|early gastrula | 26.94533| 0.5139978|    25.91|    27.71| 201.0156| 187.5445|    0.81|  613.60|\n|prawnchip      | 26.79206| 0.3650893|    26.17|    27.84| 154.3572| 619.0712|    0.00| 8069.12|\n\n</div>\n:::\n:::\n\n::: callout-caution\nThe lab incubation temperature conditions were:\n\n- cleavage 26.87 +/- 0.23 C (min 26.08, max 27.24)\n- prawnchip 26.79 +/- 0.36 C (min 26.17, max 27.84) \n- early gastrula 26.94 +/- 0.51 C (min 25.91, max 27.71)\n\nThe lab incubation lux conditions were:\n\n- cleavage 151.7127 +/- 161.39 lux (min 0, max 409.28)\n- prawnchip 154.35 +/- 619.07 lux (min 0, max 8069.12)\n- early gastrula 201.01 +/- 187.54 (min 0.81, max 613.60)\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlab_incubation <- all_incubation %>%\n  filter(!is.na(stage)) %>% # remove rows where stage is missing\n  filter(space == \"lab\")\n\n# Check homogeneity of variance\nleveneTest(temp ~ stage, data = lab_incubation)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      |  Df| F value| Pr(>F)|\n|:-----|---:|-------:|------:|\n|group |   2| 73.8332|      0|\n|      | 585|      NA|     NA|\n\n</div>\n:::\n:::\n\n::: callout-caution\nOur data has unequal variances so we use Welch's t-test for ANOVA\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Welch's ANOVA comparing temperature by stage\nwelch_anova <- oneway.test(temp ~ stage, data = lab_incubation, var.equal = FALSE)\nprint(welch_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne-way analysis of means (not assuming equal variances)\n\ndata:  temp and stage\nF = 5.9606, num df = 2.00, denom df = 320.16, p-value = 0.002873\n```\n\n\n:::\n:::\n\nFollow up the Welch's t-test with a post-hoc test\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npairwise_results <- pairwise.t.test(\n  x = lab_incubation$temp,\n  g = lab_incubation$stage,\n  p.adjust.method = \"bonferroni\",\n  pool.sd = FALSE\n)\nprint(pairwise_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using t tests with non-pooled SD \n\ndata:  lab_incubation$temp and lab_incubation$stage \n\n               cleavage early gastrula\nearly gastrula 0.2608   -             \nprawnchip      0.0269   0.0037        \n\nP value adjustment method: bonferroni \n```\n\n\n:::\n:::\n\n\n::: callout-caution\nPairwise comparisons of temperature across stage using Welch’s t-tests with Bonferroni-adjusted p-values revealed the temperatures experienced during the latest embryonic stage (early gastrula) are significantly different from the prawnchip stage (p<0.05). **HOWEVER, the actual temperature range experienced across embryonic development (26.79-26.94) is within the ambient seawater range and is ecologically parallel to the natural sea surface temp fluctuations experienced in a diurnal cycle.**\n:::\n\n## Is lab temp different across spawn night?\nAdd a column that indicates the spawn night (1, 2, or 3)\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlab_incubation <- lab_incubation %>%\n  mutate(\n    spawn = case_when(\n      datetime >= incubation_windows$start[1] & datetime <= incubation_windows$end[1] ~ 1,\n      datetime >= incubation_windows$start[2] & datetime <= incubation_windows$end[2] ~ 2,\n      datetime >= incubation_windows$start[3] & datetime <= incubation_windows$end[3] ~ 3,\n      TRUE ~ NA_integer_\n    )\n  )\n```\n:::\n\nPrint a table of temps and lux by spawn night\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nby_spawn <- lab_incubation %>%\n  group_by(spawn) %>%\n  summarize(\n    avg_temp = mean(temp, na.rm = TRUE),\n    sd_temp = sd(temp, na.rm = TRUE),\n    min_temp = min(temp, na.rm = TRUE),\n    max_temp = max(temp, na.rm = TRUE),\n    avg_lux = mean(lux, na.rm = TRUE),\n    sd_lux = sd(lux, na.rm = TRUE),\n    min_lux = min(lux, na.rm = TRUE),\n    max_lux = max(lux, na.rm = TRUE)\n  )\n\nby_spawn\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n| spawn| avg_temp|   sd_temp| min_temp| max_temp|  avg_lux|   sd_lux| min_lux| max_lux|\n|-----:|--------:|---------:|--------:|--------:|--------:|--------:|-------:|-------:|\n|     1| 27.23163| 0.2814402|    26.60|    27.84| 213.6418| 594.5645|       0| 8069.12|\n|     2| 26.85444| 0.2351807|    26.21|    27.24| 149.9682| 167.1667|       0|  472.48|\n|     3| 26.52658| 0.2326195|    25.91|    27.24| 139.2350| 176.6241|       0|  613.60|\n\n</div>\n:::\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlab_incubation <- lab_incubation %>% \n  mutate(spawn = factor(spawn, levels = c(1, 2, 3), \n                        labels = c(\"1\", \"2\", \"3\")))  # convert spawn to factor with labels\n# Check homogeneity of variance\nleveneTest(temp ~ spawn, data = lab_incubation)\n```\n\n::: {.cell-output-display}\n<div class=\"kable-table\">\n\n|      |  Df|  F value|   Pr(>F)|\n|:-----|---:|--------:|--------:|\n|group |   2| 10.11787| 4.79e-05|\n|      | 585|       NA|       NA|\n\n</div>\n:::\n:::\n\n::: callout-caution\nOur data has unequal variances so we use Welch's t-test for ANOVA\n:::\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Welch's ANOVA comparing temperature by stage\nwelch_anova <- oneway.test(temp ~ spawn, data = lab_incubation, var.equal = FALSE)\nprint(welch_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne-way analysis of means (not assuming equal variances)\n\ndata:  temp and spawn\nF = 366.72, num df = 2.00, denom df = 387.43, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\nFollow up the Welch's t-test with a post-hoc test\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npairwise_results <- pairwise.t.test(\n  x = lab_incubation$temp,\n  g = lab_incubation$spawn,\n  p.adjust.method = \"bonferroni\",\n  pool.sd = FALSE\n)\nprint(pairwise_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPairwise comparisons using t tests with non-pooled SD \n\ndata:  lab_incubation$temp and lab_incubation$spawn \n\n  1      2     \n2 <2e-16 -     \n3 <2e-16 <2e-16\n\nP value adjustment method: bonferroni \n```\n\n\n:::\n:::\n\n::: callout-caution\nPairwise comparisons of temperature across spawn night using Welch’s t-tests with Bonferroni-adjusted p-values revealed that each night is significantly different (p<2.2e-16). **HOWEVER the actual range of temps across all three spawn nights is 26.5 to 27.2 (less than 1C), and is an ecological parallel to actual fluctuations in sea surface temp that occur across nights of spawning.**\n:::\n\n# Summary\n**Temperature**\nAlthough statistically significant differences in temperature were detected across both spawn nights (with temperatures generally decreasing over the three nights) and developmental stage (with the lowest temperatures observed just before dawn during the prawnchip stage, but no significant difference between the cleavage and early gastrula stages), the magnitude of these differences was small and remained within the normal range of ambient seawater temperature fluctuations observed during a spawning event. Therefore, while temperature varied somewhat across the experimental assay, this variation is minor and unlikely to confound our results, as embryos in nature develop under similar thermal conditions.\n\n**Light**",
    "supporting": [
      "bench-incubation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}