---
title: "Kip's Capstone Round"
subtitle: "Our first attempt at generating response curves of anemone respiration & photosynthesis  to increasing levels of PVC and PP leachate"
author: "Sarah Tanja"
date: '04/24/2024'
categories: [anemones, records]
draft: false
toc: true
toc-title: Contents <i class="bi bi-bookmark-heart"></i>
toc-depth: 5
toc-location: left
reference-location: margin
citation-location: margin
link-external-icon: true
link-external-newwindow: true
bibliography: ../anemone-leachate-heat.bib
---

## Tentacle snip

For an anemone muscle relaxant make 500mL of 0.3M MgCl~2~. The final muscle relaxant will be a 1:1 ratio of the 0.3M MgCl~2~ and filtered seawater, so this will give us a total of 1L of solution to use across the experiment.

I used Fisher Chemical [Magnesium Chloride Hexahydrate](https://www.fishersci.com/shop/products/magnesium-chloride-hexahydrate-crystalline-certified-acs-fisher-chemical-2/M33500?gclid=CjwKCAjw26KxBhBDEiwAu6KXtxq6G-tMIxhF3_cyBB4bln-A5ZBd3e-x4zQmiUhtrWKL8hAWeDhDbhoCg1MQAvD_BwE&ef_id=CjwKCAjw26KxBhBDEiwAu6KXtxq6G-tMIxhF3_cyBB4bln-A5ZBd3e-x4zQmiUhtrWKL8hAWeDhDbhoCg1MQAvD_BwE:G:s&s_kwcid=AL!3652!3!380738286232!!!g!!&gad_source=1) , CAS 7791-18-6

Use the molar mass[^1] of Magnesium Chloride Hexahydrate (203.33g) to calculate how much salt we need to add to DI water to make 500mL of 0.3M MgCl~2~

[^1]: Learn how to calculate it yourself in this quick [youtube video](https://www.google.com/search?q=molar+mass+MgCl2+6H2O&rlz=1C1CHBF_enUS973US973&oq=molar+mass+MgCl2+6H2O&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIICAEQABgWGB4yDQgCEAAYhgMYgAQYigUyDQgDEAAYhgMYgAQYigXSAQkyMjYwNmowajeoAgiwAgE&sourceid=chrome&ie=UTF-8#fpstate=ive&vld=cid:cf42848d,vid:p8RZ_f0e7Fc,st:3) or just believe the number given on the chemical bottle label (it's the same)

> $$
> n = Mv
> $$ where:
>
> n = moles
>
> M = molar concentration
>
> v = volume in liters

So to find the recipe for 0.3M MgCl~2~

Calculate how many moles are in 500mL (0.5L):

$$
n = 0.3M\, \text{MgCl}_{2}\cdot0.5L \\
n = 0.15\, \text{moles}
$$

And calculate how many grams are in 0.15 moles:

```{r}
203.33*0.15
```

$$
\text{mass}(g) = \text{molar mass}\,(g) \cdot \text{moles} \\
\text{mass}(g) = 203.33\,(g) \cdot 0.15\, moles \\
 \text{mass}(g) = 30.50
$$

SO we add 30.5 grams of MgCl~2~ to a 500mL reagent bottle, and then fill it until a total volume of 500mL is reached. *Voila!*
