---
title: "The aggregating anemone, Anthopleura elegantissima"
author: "Sarah Tanja"
date: '05/02/2024'
categories: [anemones]
draft: false
toc: true
toc-title: Contents <i class="bi bi-bookmark-heart"></i>
toc-depth: 5
toc-location: left
reference-location: margin
citation-location: margin
link-external-icon: true
link-external-newwindow: true
bibliography: anemones.bib
---

*Anthopleura elegantissima*

> "This anemone is an effective predator living in zooplankton-rich water, so one would not expect it to be as nutrient-limited, nor as dependent on algal photosynthetic productivity as its tropical symbiotic counterparts. It is also adapted to prolonged aerial exposure and greater temperature extremes; the animal feeds and its symbionts photosynthesize at temperatures approaching 5°C." - @mccloskey1996

In the paper by @mccloskey1996 the anemone's were fed every other day with \~30mg of freshly hatched *Artemia nauplii* and maintained for 22 days with a single anemone each in its own 100mL jar, with seawater replaced every other day at 14°C ±2°C.

Normally, *A. elegantissima* expels symbionts from its coelenteron in a bolus of mucus and undigested material. Expulsion of symbionts should not be confused with "bleaching" phenomenon in reef corals, and may serve an ulterior purpose and undergo a different process. The anemones 'cull' or 'weed' the symbionts to maintain an optimal symbiont population density.

The optimized symbiont density is reported in the literature as 10^6^ cells·mg^-1^ of host protein and 1-5·10^6^ cells·cm^-2^ [@mccloskey1996].

> Sea anemones of the genus Anthopleura along northeast Pacific intertidal shores engage in a particularly unique symbiosis with two especially phylogenetically and physiologically different symbionts: the chlorophyte *Elliptochloris marina* (Letsch et al., 2009) and the dinoflagellate *Symbiodinium muscatinei* (LaJeunesse and Trench, 2000). - @dimond2017

Most anemones only host one symbiont, or the other. It is rare for mixed assemblages of the two 'symbiont morphs' to occur. In the paper by @mccloskey1996, they found that among 91 anemones, \>95% had a single symbiont type. The chlorophyte *Elliptochloris marina* is relatively sensitive to light and is limited to cooler, low light environments typical of the low intertidal. The dinoflagellate *Symbiodinium muscatinei*, on the other hand, tolerates higher light and temperatures and is more comonly found in anemones in the upper intertidal zone. Aposymbiotic (non-symbiont forming) *A. elegantissima* anemones can be found thriving in very low light conditions like inside rocky crevasses within the intertidal zone. Transplantation of *A. elegantissima* anemones with chlorophyte *E. marina* symbionts to warmer, higher-light environments results in shifts in the symbiont to the dinoflagellate *S. muscatinei* [@dimond2017].

Anemones hosting *Symbiodinium muscatinei* have a golden-brown color, while those that host *Elliptochloris marina* are mossy green. Symbiont type can be verified by viewing excised tentacles under light microscopy, and commonly, no mixed-symbiont populations are observed [@dimond2017].

In the study by @dimond2017, anemones were housed in 200mL glass beakers in a seawater flow-through tank as a bath, with the water level just below the top of the beakers.

Based on metrics including photosynthetic rate, mitotic index, chlorophyll content, and population density, several studies have concluded that while S. muscatinei is tolerant of a broad range of environmental
