---
title: "Management Background"
subtitle: "Puget Sound's kelp and eelgrass management and environmental landscapes across the decades"
format: html
---

The Salish Sea is a bioregion encompassing the inland marine waterways of British Columbia and Washington State's watersheds. The Puget Sound is the southern portion of the Salish Sea that falls within Washington State inland marine waters. The Puget Sound is a fjord-formed estuary, a place where freshwater from rivers and watershed mixes with saltwater from the ocean.

# 1988 National Estuary Program

Congress created the National Estuary Program (NEP) in 1987 and initiated Puget Sound as an Estuary of National Significance in 1988. Puget Sound is the 2nd largest estuary in the U.S (after Chesapeake Bay).

# 2000 Joint Statement of Cooperation

In 2000, the EPA and Environment and Climate Change Canada signed a *J[oint Statement of Cooperation](https://www.epa.gov/puget-sound/us-canada-cooperation-salish-sea)* that commits to work collaboratively to achieve common goals. This agreement calls for the two agencies to develop and periodically update a [Salish Sea Action Plan](https://www.epa.gov/puget-sound/us-canada-cooperation-salish-sea), often titled Canada - U.S. Cooperation in the Salish Sea Action Plan. This plan focuses on

Current advisory members represent the following organizations:

- Coast Salish Gathering Steering Committee

- British Columbia Ministry of Water, Land and Resource Stewardship

- British Columbia Ministry of Environment and Parks

- Washington State Department of Ecology

- Puget Sound Partnership

- Northwest Straits Commission

- Salish Sea Institute at Western Washington University

# 2007 Puget Sound Partnership

The Washington State Legislature created the Puget Sound Partnership in 2007 as a state agency assigned to coordinating and leading restoration and protection efforts in Puget Sound. Read more about Puget Sound Partnership's role [here](https://www.psp.wa.gov/nep-overview.php).

> Collectively, the governments, organizations, businesses, and individuals engaged in Puget Sound recovery are called the **Management Conference**; which uses a collaborative, consensus-building approach to develop and implement the Puget Sound Action Agenda.

## Puget Sound Action Agenda

The Puget Sound Partnership curates the [Puget Sound Action Agenda](https://www.psp.wa.gov/2022AAupdate.php) which is the Management Conference's shared plan for recovery. The Puget Sound Action Agenda is re-worked every four years in a cycle meant to continually assess priorities, incorporate the best available science, and respond to the needs, concerns, and guidance of the Management Conference. The Puget Sound Action Agenda doubles as the Comprehensive Conservation Management Plan (CCMP), which is a statutory mandate tied to the designation as an Estuary of National Significance and funding from the NEP.

## Puget Sound Ecosystem Monitoring Program (PSEMP)

The Puget Sound Partnership financially supports the PSEMP, which is a collaborative network of subject matter experts from many monitoring organizations throughout the region. Together, they generate and communicate scientific information to track Puget Sound ecosystem conditions.

## Puget Sound Acquisition and Restoration Fund (PSAR)

Puget Sound Partnership and Washington State Recreation and Conservation Office co-administers the Puget Sound Acquisition and Restoration (PSAR) fund, which supports projects that recover salmon and protect and recover salmon habitat in Puget Sound.

PSAR investments have helped restore and protect over 3,300 acres of estuary habitat, more than 150 miles for fish passage, and over 14,000 acres of watershed habitat. These projects support multiple benefits in addition to Puget Sound salmon, including climate resilience and flood protection, recreation, and tribal treaty rights.

# Marine Vegetation Implementation Strategy

# 2016 Puget Sound Recovery National  Program Office

Congress established the Puget Sound Recovery National Program Office within the Environmental Protection Agency (EPA) in 2016 to coordinate funding and grants from the EPA's NEP

## Health of the Salish Sea Ecosystem Report

Written by the U.S. EPA and Environment and Climate Change Canada.

## Grants and Funding

This office awards the [grants](https://www.epa.gov/puget-sound/funding-availability-puget-sound-action-agenda-strategic-implementation-leads) that are distributed through Puget Sound Partnership to each Strategic Implementation Lead (SIL). A total of \$120 million divided across the three SILs (1. Habitat, 2. Shellfish, 3. Stormwater) is provided incrementally over a five-year period. Meaning if distributed equally, each SIL would have an annual budget of \$8 million.

## Puget Sound Federal Leadership Task Force

EPA co-chairs the [Puget Sound Federal Leadership Task Force](https://www.epa.gov/puget-sound/puget-sound-federal-leadership-task-force) along with NOAA's West Coast Fisheries Regional Administrator and the U.S. Army Corps of Engineers Seattle District Commander.

## Cooperation with Canada
