---
title: "Spawn night protocol"
subtitle: "For embryonic development of Montipora capitata rice corals"
author: "Sarah Tanja"
date: '07/09/2024'
---

# Overview

This spawn night checklist was used on July 5th, 6th and 7th 2024 at the Hawaiian Institute of Marine Biology (HIMB) on Moku o Loe in Kaneohe Bay, Oahu. The overarching goal was to have a comprehensive checklist for sleep-deprived scientists to follow after 3 days of pulling nearly all-nighters to collect Montipora capitata egg-sperm bundles, conduct bundle-bundle cross fertilizations in 20mL scintillation vials, and then subsequently "Fix and Freeze" the embryos at 4 hours post fertilization (hpf) when fertilized eggs should be reaching initial cleavage, 9hpf when embryos should be in the 'prawn chip' phase, and 14hpf when embryos should be in the early gastrula phase. The end goal is to see if low levels of PVC leachate (PVC having notably larger amounts of phthalates which are known endocrine disrupting chemicals) negatively impact fertilization success and embryonic development of *Montipora capitata* embryos.

# Prep

## Make Stock Leachate

First make 400mL of each stock solution from the 1000 mg/L prepared leachate

-   [ ] Make 10 mg/L stock:

    1000 mg/L \* V1 = 10 mg/L \* 400mL

    V1 = 4mL

    400mL of 10mg/L stock = 4mL of 1000mg/L stock + 396mL of FSW

-   [ ] Make 1mg/L stock:

    10mg/L \* V1 = 1mg/L \* 400mL

    V1 = 40mL

    400mL of 1mg/L stock = 40mL of 10mg/L stock + 360mL of FSW

-   [ ] Make 0.1 mg/L stock:

    1mg/L \* V1 = 0.1mg/L \* 400mL

    V1 = 40mL

    400mL of 0.1mg/L stock = 40mL of 1mg/L stock + 360mL of FSW

## Load 20mL scintillation vials

For a 20mL scintillation vial for coral embryo experiments with a final target volume of 20mL:

**1mg/L HIGH treatment**

10mg/L \* V1 = 1mg/L \* 20mL

V1 = 2mL

20mL of 1mg/L leachate = 18mL of FSW + 2mL of 10mg/L stock

**0.1 mg/L MID treatment**

1mg/L \* V1 = 0.1mg/L \* 20mL

V1 = 2mL

20mL of 0.1mg/L leachate = 18mL of FSW + 2mL of 1mg/L stock

**0.01 mg/L LOW treatment**

0.1mg/L \* V1 = 0.01mg/L \* 20mL

V1 = 2mL

20mL of 0.01mg/L leachate = 18mL of FSW + 2mL of 0.1mg/L stock

## Dilute ZFIX

To preserve embryos for confocal microscope imaging, and visual determination of developmental stage, we have to preserve the embryo tissue and keep it from disintegrating, bursting, shredding... etc. To do that we can use ZFIX (zinc buffered formalin). There is a wide range (4-20%!) reported in the literature of ZFIX or paraformaldehye concentrations used for tissue preservation. We chose to work with 4% ZFIX. Some constraints we took into account are that FedEx will let you ship any volume of formalin as long as it's below 10% concentration, and the less concentrated... the 'safest' it is for us to handle.

::: callout-caution
Always handle ZFIX, formalin, paraformaldehyde, etc. in a fume hood, or a place with adequate ventilation (outside, with a stiff breeze, no huffing).
:::

Here we are going from ZFIX concentrate of 18.5% to a diluted 4% in a \~100mL final volume!

0.185 \* V1 = 0.04 \* 100mL

V1 = 21.62mL

To get 100mL of 4% ZFIX we: Added 21.62 mL of 18.5% ZFIX to 78.38mL of (0.22micron) filtered sea water

::: callout-important
Jill Ashey (personal communication) says it's important to use FSW to dilute your ZFIX! This is for long-term storage (up to 6 months) of embryos in anywhere from 4-20% ZFIX or paraformaldehyde (PFA) ... the FSW may keep your embryos from lysing so that you can preserve their integrity for microscopy. If using DI or Milli-Q water, there is a chance that the embryos become 'shriveled'. This being said... we used Milli-Q water for crosses 1-5 (before learning that FSW is best), and checked them after 48 hours. They looked perfectly preserved! We kept them in \~500uL of 4% ZFIX in micro-centrifuge tubes at 4C.
:::

# Protocol

## Bundle-Bundle Crosses

To conduct bundle-bundle crosses use transfer pipettes to take one intact bundle from each of two genetically distinct parent colonies, and pop them into a single 20mL scintillation vial loaded with the treatment condition of the assay. In this case, each scintillation vial either had only 22 micron filtered seawater (control - 0 mg/L PVC leachate), a low environmental dose (low - 0.01 mg/L PVC leachate), a mid dose (mid - 0.1 mg/L PVC leachate), or a high dose (1mg/L PVC leachate). Each 'n' set of treatments, embryonic phases, and sample types (microscopy and molecular) should try to have the same genetic cross (aka same set of parent colonies).

::: callout-note
Twice (once attempting this in 2022, and once in 2024) I noticed poor viability and cross-fertilization success when attempting to cross *Montipora capitata* colonies that are growing on the Padilla-Gamino Lab "racks"... these colonies have been growing in proximity to each other since 2017. Crosses between "rack" colonies and "wild" colonies, as well as "wild-wild" crosses seem fine... but here, we avoided "rack-rack" colony crosses, as they proved to result in poor fertilization success.
:::

As soon as bundles begin to hydrate and 'break-up', the ability to do bundle-bundle crosses ends. This gives you a very short (1 hour!) window, as spawning typically starts around \~8:45 - 9:15 PM, and bundles begin hydrating and breaking up \~10:00 - 10:40 PM. we found that a single person can feasibly cross 120 scintillation vials in this timeframe. In our experimental design, that translates to an 'n' of 5, or 5 'crosses' each night of spawning.

## Fix (microscopy)

To fix embryos for later microscopic inspection we

## Freeze (molecular)

To preserve embryos for RNA extraction and sequencing we will first submerge them in Zymo DNA/RNA Shield, and then pronptly transfer them to a -80C freezer. Here, we won't be dunking them in LN2. The combined DNA/RNA Shield and the quick freeze (due to small size) they will experience in the -80 are together sufficient for preserving RNA.

We will first very gently use a tip-clipped transfer pipette to transfer embryos to our 0.5mL screw-cap cryo-tubes. We will then carefully decant any excess FSW out of the tube, and then add 500uL of Zymo RNA/DNA Shield. Gently invert cryo-tubes a few times to ensure embryos are fully submerged. Once cryo-tubes are filled with their samples, arrange them in wax paper boxes and promptly shift them to -80°C freezer for storage until samples are ready to be processed.

# Spawn Night Checklist

### 19:00 - 19:30

-   [ ] Move each colony to a numbered/named cambro chamber bin or 5 gallon bucket
-   [ ] Ensure each colony has enough headspace so that bundles can rise to the surface
-   [ ] Reduce blue holding tank water level to below the lip of the chambers
-   [ ] Decant water in chambers such that bouyant bundles don't spill out

### 19:30 - 20:00

-   [ ] Organize the following collection materials at the spawning tubs:

    -   [ ] 50mL falcon tubes (1 for ea. colony) filled with 30mL of 0.22micron[^1] FSW
    -   [ ] Tip-clipped[^2] transfer pipettes
    -   [ ] Red Headlamps (new batteries)
    -   [ ] Printed waterproof spawn collection data sheet

-   [ ] Organize the following collection materials at the dry lab bench:

    -   [ ] 20mL scintillation vials prepped with treatments

    -   [ ] 50mL falcon tube rack (for working with active bundle-bundle crosses)

    -   [ ] Transfer pipettes (for moving bundles to scintillation vials)

    -   [ ] Printed waterproof bundle-bundle cross metadata sheet (for recording parent colonies of crosses)

[^1]: We used 0.22 micron filtered seawater, but 1.2 micron is also used for *Montipora capitata*

[^2]: 'Tip-clipped' is optional and, like it sounds, is just snipping the tip of a transfer pipette just makes the transfer pipette tip a bit wider. A normal transfer pipette is actually totally fine for collecting small quantities of individual Montipora capitata egg-sperm bundles. If you want to clip the tips, it makes it easier to suck up larger masses of egg-sperm bundles all at once.

### 20:50 - 21:20

-   [ ] Observe for setting (polyp expansion and bundle visibility) via red headlamp
-   [ ] Find a spawner!
-   [ ] Collect 24 bundles from each spawning colony and transfer them to a pre-labeled 50mL falcon tube with 30mL of FSW
-   [ ] Once we have at least 2 colonies worth of bundles, 1 person will move with any filled falcon tubes to the dry lab bench and begin bundle-bundle crosses
-   [ ] 1 person will remain and continue to collect bundles from colonies, periodically transferring them to the bundle-bundle crossing station at the dry lab bench

### 21:20 - 22:00

-   [x] Cross fertilize by taking one bundle each from two distinct colonies and transferring them to the same scintillation vial
-   [x] Record the parent colonies of each cross on the embryonic development metadata sheet
-   [x] Only transfer intact bundles! Once eggs break up and begin to hydrate, the spawn party is over

### 22:00 - 22:30

-   [ ] Observe scintillation vials for bundle breakup and egg hydration

-   [x] Record the times when the first and last vials experience hydration

    -   [x] First Egg Hydration Time\_\_\_\_\_22:00\_\_\_

    -   [x] Last Egg Hydration Time\_\_\_\_\_22:40\_\_\_

-   [x] Average the times above , and add 4 hours, 9 hours, and 14 hours

    -   [x] Average Egg Hydration Time\_\_\_22:20\_\_\_

    -   [x] 4 hours post-fertilization[^3]\_\_\_\_\_02:20\_\_\_\_

    -   [x] 9 hours post-fertilization\_\_\_\_\_\_07:20\_\_\_\_

    -   [x] 14 hours post fertilization\_\_\_\_\_\_12:20\_\_\_

-   Set alarms for \~40 minutes prior to the times above to wake and 'fix and freeze' each set

[^3]:
    -   [ ] (& on July 6th make another batch of leachate!)

### 22:30 - 23:00

-   [ ] Return each colony to blue tank and remove chambers

-   [ ] Return water height to normal

-   [ ] Clean up anything left outside

### 23:00 - 01:45

-   [ ] 2.5 hr nap time!

### 02:15 - 03:30

-   [ ] ZFIX 4hpf samples (4Z)

    -   [ ] Use a transfer pipette to gently move embryos from scintillation vials to microcentrifuge tubes
    -   [ ] Decant any excess FSW with transfer pipette
    -   [ ] Add \~1mL of 4% ZFIX to each microcentrifuge tube in the fume hood!
    -   [ ] Gently invert each capped scintillation vial to mix the ZFIX into the filtered seawater and sample
    -   [ ] Set fixed vials in 4C fridge

-   [ ] Freeze 4hpf samples (4F)

    -   [ ] Gently transfer live embryos to cryo-vials
    -   [ ] Decant excess FSW using a transfer pipette
    -   [ ] Add 500uL of Zymo DNA/RNA Shield
    -   [ ] Promptly transfer to -80C freezer

-   [ ] Make PVC Leachate (on July 6th!)

### 03:30 - 06:45

-   [ ] 3.25 hr nap time!

### 07:15 - 08:30

-   [ ] ZFIX 9hpf samples (9Z)

    -   [ ] Use a transfer pipette to gently move embryos from scintillation vials to microcentrifuge tubes
    -   [ ] Decant any excess FSW with transfer pipette
    -   [ ] Add \~0.5 - 1mL of 4% ZFIX to each microcentrifuge tube in the fume hood!
    -   [ ] Gently invert each capped scintillation vial to mix the ZFIX into the filtered seawater and sample
    -   [ ] Set fixed vials in 4C fridge

-   [ ] Freeze 9hpf samples (9F)

    -   [ ] Gently transfer live embryos to cryo-vials

    -   [ ] Decant excess FSW using a transfer pipette

    -   [ ] Add 500uL of Zymo DNA/RNA Shield

    -   [ ] Promptly transfer to -80C freezer

### 08:30 - 11:45

-   [ ] 3.25 hr nap time!

### 12:15 - 13:30

-   [ ] ZFIX 14hpf samples (14Z)

    -   [ ] Use a transfer pipette to gently move embryos from scintillation vials to microcentrifuge tubes
    -   [ ] Decant any excess FSW with transfer pipette
    -   [ ] Add \~1mL of 4% ZFIX to each microcentrifuge tube in the fume hood!
    -   [ ] Gently invert each capped scintillation vial to mix the ZFIX into the filtered seawater and sample
    -   [ ] Set fixed vials in 4C fridge

-   [ ] Freeze 14hpf samples (14F)

    -   [ ] Gently transfer live embryos to cryo-vials

    -   [ ] Decant excess FSW using a transfer pipette

    -   [ ] Add 500uL of Zymo DNA/RNA Shield

    -   [ ] Promptly transfer to -80C freezer

::: callout-tip
You can do this!
:::
