---
title: "Statistics for embryo scope data"
subtitle: "Exploring data from embryonic development of Montipora capitata rice corals exposed to PVC leachate"
author: "Sarah Tanja"
date: 09/06/2024
date-format: long
date-modified: today
categories: [stats, coral]
toc: true
toc-title: Contents <i class="bi bi-bookmark-heart"></i>
toc-depth: 5
toc-location: left
reference-location: margin
citation-location: margin
link-external-icon: true
link-external-newwindow: true
---

What information can we get from looking at the *Montipora capitata* embryos that were exposed to varying levels of PVC leachate (High: 1mg/L, Mid: 0.1mg/L, Low: 0.01mg/L)? This experiment allowed embryos to develop from a bundle-bundle cross (meaning one egg-sperm bundle from one parent colony was placed in a 20mL scintillation vial with another egg-sperm bundle from a different parent colony). Colonies are not known to be able to self-fertilize... meaning it's important that each bundle came from a different parent colony. Each *Montipora capitata* egg sperm bundle contains a 'bundle' of eggs that are bound together around a 'packet' of sperm.

| variable                                | unit/type                                | statistical test           |
|-----------------------------------------|------------------------------------------|----------------------------|
| embryo size                             | microns, continuous variable             | One-Way ANOVA              |
| embryo stage                            | cell stage, ordinal categorical variable | Chi-Square Goodness of Fit |
| proportion of abnormality per cross     | ratio, continuous variable               |                            |
| proportion of abnormality per treatment | ratio, continuous variable               |                            |
| proportion of fertilization success     | ratio, continuous variable               |                            |

> If you take pics of X random embryos for every cross, you can get:
>
> 1.  Embryo size (unit: microns/mm, continuous variable)
> 2.  Embryo stage (cell stage, ordinal categorical variable)
> 3.  Abnormality (yes/no, binary categorical variable)
> 4.  Proportion of abnormality per cross (ratios, continuous variable), which you can use to obtain % abnormality per treatment
>
> You can also assess
>
> 5.  Fertilization success (yes/no per cross, binary categorical variable)
> 6.  Fertilization success (proportion per treatment, ratios, continuous variable)

# How do we assess proportion of fertilization success?
