---
title: "Corals in a hot plastic ocean"
subtitle: "How heat and phthalates shift a Montipora capitata coral microbiome"
author: "Sarah Tanja"
date: '10/10/2023'

format: 
  revealjs:
    slide-number: true
    chalkboard: 
      buttons: false
    preview-links: auto
    theme: simple
    footer: "Sarah Tanja (stanja@uw.edu)"
    
categories: [presentations]
draft: false
---

## {background-image="images/plastic_monster_celine_bellanger_UN_plastic_is_forever.jpg"} 

::: footer
Learn more: [Plastic monster, France Photo by Céline Bellanger for the United Nations Environmental Programme (UNEP) Plastic is Forever Exhibit ](https://www.un.org/en/exhibits/exhibit/in-images-plastic-forever)
:::

`8 million tons` of plastics enter the oceans `every year`

::: {.notes}
Today I am going to talk about phthalates, thermal stress and the microbiome of Montipora capitata corals... and while this talk will get deep into the nitty-gritty weeds of genomics and physiology (don't worry, yes we will get there), I want to start by acknowledging that this research was motivated by the dual global challenges of marine plastic pollution and ocean warming.

Like this art piece by photographer Celine Bellanger on the coast of France depits, this is the monster we are fighting
:::

## Media Backgrounds {background-image="images/plastic_monster_celine_bellanger_UN_plastic_is_forever.jpg"}

You can also use the following as a slide background:

-   An image: `background-image`

-   A video: `background-video`

-   An iframe: `background-iframe`

::: footer
Learn more: [Media Backgrounds](https://quarto.org/docs/presentations/revealjs/#image-backgrounds)
:::

## Slide Backgrounds {background="#43464B"}

Set the `background` attribute on a slide to change the background color (all CSS color formats are supported).

Different background transitions are available via the `background-transition` option.

::: footer
Learn more: [Slide Backgrounds](https://quarto.org/docs/presentations/revealjs/#color-backgrounds)
:::


## Incremental Lists

Lists can optionally be displayed incrementally:

::: incremental
-   First item
-   Second item
-   Third item
:::

. . .

<br/> Insert pauses to make other types of content display incrementally.

::: footer
Learn more: [Incremental Lists](https://quarto.org/docs/presentations/revealjs/#incremental-lists)
:::