---
title: "Summary of previous research on microplastic leachate exposure in marine invertebrate embryonic development"
subtitle: "In sea urchin and mussel model organisms"
author: "Sarah Tanja"
date: 10/07/2024
date-format: long
date-modified: today
categories: [learning journey, coral]
toc: true
toc-title: Contents <i class="bi bi-bookmark-heart"></i>
toc-depth: 5
toc-location: left
reference-location: margin
citation-location: margin
link-external-icon: true
link-external-newwindow: true
bibliography: ---
title: "Summary of previous research on microplastic leachate exposure in marine invertebrate embryonic development"
subtitle: "In sea urchin and mussel model organisms"
author: "Sarah Tanja"
date: 10/07/2024
date-format: long
date-modified: today
categories: [learning journey, coral]
toc: true
toc-title: Contents <i class="bi bi-bookmark-heart"></i>
toc-depth: 5
toc-location: left
reference-location: margin
citation-location: margin
link-external-icon: true
link-external-newwindow: true
#bibliography: 
---

# Jimenez-Guri et al., 2023

## **PVC pellet leachates affect adult immune system and embryonic development but not reproductive capacity in the sea urchin *Paracentrotus lividus***

@jimenez-guri2023 either exposed adult sea urchins *Paracentrotus lividus* to excessively high[^1] levels of PVC leachate or filtered seawater control for 2 weeks, and then force-spawned twice (once at the end of week 1 and once at the end of week 2) where embryos from control and exposed adults were split and incubated for development in either a filtered seawater control or a 65g/L PVC leachate (they call this 10% PVC leachate) treatment.

[^1]:
    -   1000X higher than environmental measurements in the meditereanean (Middag et al., 2022)

    -   Their 10% PVC leachate dose is 6.5g PVC pellets/100mL seawater, which is 65 grams of plastic in 1L of seawater… This compared to our 1mg/L ‘high’ dose is 65k times more highly concentrated!)

Embryos were culled at 24 and 48 hours and imaged and categorized as 'developed', 'aberrant', and 'not developed'.

> Intracellular levels of reactive oxygen species (ROS) and reactive nitrogen species (RNS) as well as total antioxidant capacity (TAC) was measured by spectrofluorometry

# Rendell-Bhatti et al., 2021

## **Developmental toxicity of plastic leachates on the sea urchin *Paracentrotus lividus***

> Using the sea urchin Paracentrotus lividus as a model, we studied the effects of leachates of three forms of plastic pellet: new industrial pre-production plastic nurdles, beached pre-production nurdles, and floating filters, known as biobeads, also retrieved from the environment. Our chemical analyses show that leachates from beached pellets (biobead and nurdle pellets) and highly plasticised industrial pellets (PVC) contain polycyclic aromatic hydrocarbons and polychlorinated biphenyls, which are known to be detrimental to development and other life stages of animals. We also demonstrate that these microplastic leachates elicit severe, consistent and treatment-specific developmental abnormalities in P. lividus at embryonic and larval stages. Those embryos exposed to virgin polyethylene leachates with no additives nor environmental contaminants developed normally, suggesting that the abnormalities observed are the result of exposure to either environmentally adsorbed contaminants or pre-existing industrial additives within the polymer matrix. In the light of the chemical contents of the leachates and other characteristics of the plastic particles used, we discuss the phenotypes observed during our study, which include abnormal gastrulation, impaired skeletogenesis, abnormal neurogenesis, redistribution of pigmented cells and embryo radialisation [@rendell-bhatti2021].

This study used the same leachate preparation and concentrations as above.

# Gambardella et al., 2024

## **High concentrations of phthalates affect the early development of the sea urchin *Paracentrotus lividus***

> The toxicity of three phthalates (PAEs) - butylbenzyl phthalate (BBP), diethyl phthalate (DEP), and di-(2-ethylhexyl) phthalate (DEHP) - was tested on the Mediterranean sea urchin Paracentrotus lividus. Fertilized eggs were exposed to environmental and high PAE concentrations for 72 h. The potential toxic effects on larval development and any morphological anomalies were then assessed to estimate PAEs impact. Environmental concentrations never affected development, while high concentrations induced toxic effects in larvae exposed to BBP (EC50: 2.9 ×103 μg/L) and DEHP (EC50: 3.72 ×103 μg/L). High concentrations caused skeletal anomalies, with a slight to moderate impact for DEP/DEHP and BBP, respectively. PAE toxicity was: BBP\>DEHP\>DEP. In conclusion, the three PAEs at environmental concentrations do not pose a risk to sea urchins. However, PAE concentrations should be further monitored in order not to constitute a concern to marine species, especially at their early developmental stages. - @gambardella2024

# Gandara e Silva et al., 2016

## **Leachate from microplastics impairs larval development in brown mussels**

> In this study, we conducted experiments to evaluate the toxicity of leachates from virgin and beached plastic pellets to embryo development of the brown mussel (Perna perna). We compared the efficiency of two test procedures, and evaluated the toxicity of beached pellets collected in a coastal marine protected area. We observed that mussel embryo is sensitive to leachate from both virgin and beached pellets. However, the toxicity of the leachate from beached pellets was much higher than that of virgin pellets. We suggest contaminants adsorbed onto the surface of beached pellets were responsible for the high toxicity of leachate from beached pellets, while the toxicity of leachate from virgin pellets was mainly due to plastic additives. Our results suggest microplastic debris may be harmful even if ingestion is not the only or main pathway of interaction of marine organisms with contaminated plastic debris. - @gandaraesilva2016

# Mincarelli et al., 2021

## **Consequences of combined exposure to thermal stress and the plasticiser DEHP in *Mytilus spp.* differ by sex**

> Little is known about the combined effect of environmental factors and contaminants on commercially important marine species, and whether this effect differs by sex. In this study, blue mussels were exposed for seven days to both single and combined stressors (i.e., +3 ◦C elevated temperature and two environmentally relevant concentrations of the plastic softener DEHP, 0.5 and 50 μg/l) in a factorial design. Males were observed to be more sensitive to high temperature, demonstrated by the significant increase in out-of-season spawning gonads and higher gene expression of the antioxidant catalase and the estrogen receptor genes. On the other hand, while the gametogenesis cycle in females was more resilient than in males, DEHP exposure altered the estrogen-related receptor gene expression. We show that the combined stressors DEHP and increased temperature, in environmentally relevant magnitudes, have different consequences in male and female mussels, with the potential to impact the timing and breeding season success in Mytilus spp. - @mincarelli2021

# Paganos et al., 2023

## **Plastic leachate-induced toxicity during sea urchin embryonic development: Insights into the molecular pathways affected by PVC**

> Here we investigate the effects of leachates from new and beach-collected pellets on the embryonic and [larval development](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/larval-development "Learn more about larval development from ScienceDirect's AI-generated Topic Pages") of the [sea urchin](https://www.sciencedirect.com/topics/pharmacology-toxicology-and-pharmaceutical-science/sea-urchin "Learn more about sea urchin from ScienceDirect's AI-generated Topic Pages") [Strongylocentrotus purpuratus](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/strongylocentrotus-purpuratus "Learn more about Strongylocentrotus purpuratus from ScienceDirect's AI-generated Topic Pages") and demonstrate that exposure of developing embryos to these leachates elicits severe, consistent and treatment-specific developmental abnormalities including radialisation of the embryo and [malformation](https://www.sciencedirect.com/topics/pharmacology-toxicology-and-pharmaceutical-science/congenital-malformation "Learn more about malformation from ScienceDirect's AI-generated Topic Pages") of the [skeleton](https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/skeleton "Learn more about skeleton from ScienceDirect's AI-generated Topic Pages"), neural and [immune cells](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/immunocompetent-cell "Learn more about immune cells from ScienceDirect's AI-generated Topic Pages"). Using a multi-omics approach we define the developmental pathways disturbed upon exposure to PVC leachates and provide a mechanistic view that pinpoints cellular [redox stress](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/redox-stress "Learn more about redox stress from ScienceDirect's AI-generated Topic Pages") and energy production as drivers of phenotypic abnormalities following exposure to PVC leachates. Analysis of leachates identified high concentrations of zinc that are the likely cause of these observed defects. Our findings point to clear and specific detrimental effects of marine [plastic pollution](https://www.sciencedirect.com/topics/earth-and-planetary-sciences/plastic-pollution "Learn more about plastic pollution from ScienceDirect's AI-generated Topic Pages") on the development of echinoderms, demonstrating that chemicals leached from plastic particles into sea water can produce strong developmental abnormalities via specific pathways, and therefore have the potential to impact on a wide range of organisms. -@paganos2023a (Abstract)

-   used nurdle beach pellets collected from Cornwall, UK & pre-production commercial PVC nurdles

> These results are consistent with those observed previously in P. lividus, where beached and PVC pellet leachates elicited changes including abnormal gastrulation, impaired skeletogenesis, abnormal neurogenesis and embryo radialisation (Rendell-Bhatti et al., 2020), indicating that these types of developmental abnormalities may not be species-specific but affect the whole clade similarly. The PVC treatment-induced phenotype was of particular interest as it clearly resembles the one obtained when the specification of the secondary axis of the sea urchin embryo (oral-aboral) is disturbed. Similar to our P. lividus data (Rendell-Bhatti et al., 2020), **embryos exposed to PVC leachates are unable to produce a proper skeleton.** In normal gastrula embryos, skeletogenic cells are spatially organised around the archenteron, forming a syncytium to which biominerals are deposited (Fig. 2. E). At the pluteus stage, the larval skeleton consists of different skeletal rods that are responsible for the characteristic shape of the larvae (Fig. 2. F). PVC leachate-treated S. purpuratus gastrulae seem to be missing differentiated skeletogenic cells as indicated by the absence of the skeletal marker MSP130 immunoreactivity (Fig. 2. I), while the same marker at 72 hpf reveals the presence of radialised syncytium of differentiated skeletogenic cells (Fig. 2. J). Another visible abnormality of the treated larvae is the absence of a well-formed ciliary band, an observation confirmed by the β-tubulin staining showing a reduced ciliary surface when compared to controls (Fig. 2. G, H). **Esophageal muscles originate from myoblasts that at gastrula stage populate the tip of the embryonic foregut and at the pluteus stage they differentiate towards circumesophageal muscles controlling the contraction of the sea urchin esophageal region and therefore feeding** (Andrikou et al., 2013, 2015). Immunohistochemical staining for the esophageal muscles marker Sp-MHC revealed that **exogastrulated larvae are lacking any muscular structure** suggesting that exogastrulation impaired muscle development (Fig. 2. K, L). In the Rendell-Bhatti et al. (2020) study we found PCB and PAH in the leachates of environmental samples, and PAH and HCB in PVC leachates, which we suggested were the possible causes of the malformations observed (Rendell-Bhatti et al., 2020). We had not observed exogastrulas before, but another study had found otherwise well-formed P. lividus pluteus larvae with everted gut rudiments when exposed to micronized plastic toys (Oliviero et al., 2019). However, **the phenotypes here observed in the PVC treatments clearly mirror phenotypes from classical and new experiments exposing S. purpuratus and other sea urchins to heavy metals** (Mitsunaga and Yasumasu, 1984; Kobayashi and Okamura, 2004; Cunningham et al., 2020), as well as to **oral-aboral axis formation disorganisation** (Duboc et al., 2004). Indeed, we see radialised/oralised embryos similar to those described when the developmental pathways involved in oral/aboral (O/A) and left/right (L/R) axis formation are disrupted (Duboc et al., 2004, 2008). These results prompted us to investigate what transcriptomic changes were taking place in the embryos to be able to identify the mechanisms by which the plastic leachates were affecting development. -@paganos2023a

-   disturbs differentiation of skeletogenic cells

-   disturbs formation of ciliary band, esophageal region for feeding

-   disturbs oral-aboral & left-right axis formation

-   mirrors effects of exposure to heavy metal, esp. zinc

> "down-regulated genes represented \>75 % of the differentially expressed genes (86 % at 48 hpf and 77 % at 72 hpf) suggesting that the effect by PVC leachates is of repressive nature, leading to a developmental program failure" -@paganos2023a

> To analyse what type of processes are altered in the treated embryos we performed a gene ontology (GO) enrichment analysis using ShinyGO 0.76 platform (Ge et al., 2020) followed by REVIGO (Supek et al., 2011) to reduce redundant terms and visualise the data, separately for up- and down-regulated genes and each time point. -@paganos2023a

-   More downregulated genes than upregulated

Overrepresented GO terms for both up and down regulated genes

At 48hpf:

\- detection and response to stimuli

\- signaling pathways

\- development and developmental processes

\- metabolic and biosynthetic processes

\- regulation of processes and transport

At 72 hpf:

\- metabolic processes

\- regulation and development

> Moreover, for up-regulated genes we see response to external stimuli and cell organisation GO terms overrepresented, while for down-regulated genes we find signaling pathways and transport overrepresented. -@paganos2023a

# Xiao et al., 2018

## Transcriptional responses of *Acropora hyacinthus* embryo under the benzo(*a*)pyrene stress by deep sequencing

> Abstract
>
> Coral embryos are a critical and sensitive period for the early [growth and development](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/growth-development-and-aging "Learn more about growth and development from ScienceDirect's AI-generated Topic Pages") of coral. Benzo(*a*)pyrene (BaP) is widely distributed in the ocean and has strong toxicity, but there is little information on the toxic effects to coral embryos exposed to this widespread environmental contaminant. Thus, in this study, we utilized the Illumina Hiseq™ 4000 platform to explore the gene response of [Acropora](https://www.sciencedirect.com/topics/pharmacology-toxicology-and-pharmaceutical-science/acropora "Learn more about Acropora from ScienceDirect's AI-generated Topic Pages") *[hyacinthus](https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/hyacinthus "Learn more about hyacinthus from ScienceDirect's AI-generated Topic Pages")* embryos under the BaP stress. A total of 130,042 [Unigenes](https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/unigenes "Learn more about Unigenes from ScienceDirect's AI-generated Topic Pages") were obtained and analyzed, and approximately 37.67% of those matched with sequences from four different species. In total, 2606 Unigenes were up-regulated, and 3872 Unigenes were down-regulated. After [Gene Ontology](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/gene-ontology "Learn more about Gene Ontology from ScienceDirect's AI-generated Topic Pages") (GO) annotation, the results show that the “cellular process” and “metabolic process” were leading in the category of [biological processes](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/biological-phenomena-and-functions-concerning-the-entire-organism "Learn more about biological processes from ScienceDirect's AI-generated Topic Pages"), which the “binding” and “catalytic activity” were the most abundant subcategories in molecular function. Based on the Kyoto Encyclopedia of Genes and Genomes (KEGG) analysis, the most differentially expressed genes (DEGs) were enriched, as well as down-regulated in the pathways of [oxidative phosphorylation](https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/oxidative-phosphorylation "Learn more about oxidative phosphorylation from ScienceDirect's AI-generated Topic Pages"), metabolism of [xenobiotics](https://www.sciencedirect.com/topics/pharmacology-toxicology-and-pharmaceutical-science/xenobiotic-agent "Learn more about xenobiotics from ScienceDirect's AI-generated Topic Pages"), immune-related genes, [apoptosis](https://www.sciencedirect.com/topics/agricultural-and-biological-sciences/programmed-cell-death "Learn more about apoptosis from ScienceDirect's AI-generated Topic Pages") and human disease genes. At the same time, 388,197 of Single-nucleotide Polymorphisms (SNPs) and 6164 of [Simple Sequence Repeats](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/microsatellite-dna "Learn more about Simple Sequence Repeats from ScienceDirect's AI-generated Topic Pages") (SSRs) were obtained, which can be served as the richer and more valuable SSRs [molecular markers](https://www.sciencedirect.com/topics/biochemistry-genetics-and-molecular-biology/genetic-marker "Learn more about molecular markers from ScienceDirect's AI-generated Topic Pages") in the future. The results of this study can help to better understand the [toxicological mechanism](https://www.sciencedirect.com/topics/pharmacology-toxicology-and-pharmaceutical-science/toxicological-mechanisms "Learn more about toxicological mechanism from ScienceDirect's AI-generated Topic Pages") of coral embryo exposed to BaP, and it is also essential for the protection and restoration of coral reef ecosystem in the future.
