---
title: "Anemone Project Planning"
author: "Sarah Tanja"
date: '01/02/2024'
categories: [anemones]
draft: false
toc: true
toc-title: Contents <i class="bi bi-bookmark-heart"></i>
toc-depth: 5
toc-location: left
reference-location: margin
citation-location: margin
link-external-icon: true
link-external-newwindow: true
bibliography: ../anemone-leachate-heat.bib
---

## Conceptual planning

### Problem

-   Marine microplastics are an emerging pollutant of concern that have only been widely 'in play' for the last 80 years

-   They're more complicated than you might think, they are full of chemicals that are not covalently bound to them, and the chemicals leach out, we call this leachate

-   Very little is known about the impacts of this type of pollution because it's hard to study (plastics are everywhere!), and as stated previously, it's only been around for the last 80 years coinciding with increased plastic production and integration into consumer products

### Here's what we do know

-   ***A. elegantissima*** **is very tolerant to a broad range of thermal exposures.** As an intertidal organism, *A. elegantissima* regularly experience large temperature shifts throughout the day coinciding with desiccation at low tide. They are found from Baja, California to Southeast Alaska, and in anemones hosting the brown alga *Breviolum muscatinei*, temperatures from 6^o^C to 24^o^C do not significantly affect their algal density, mitotic index, or total chlorophyll (a + c), but net photosynthesis and anemone respiration both increase with temperature [@Verde.2002].

-   ***A. elegantissima*** **gains symbionts through horizontal transmission** [@lajeunesse2000a]**. (Trench 1987)**

### What we don't know

-   We don't know if/how microplastic leachate affects Cnidarians

-   We don't know if/how microplastic leachate affects Cnidarians in the context of multiple stressors (i.e. a marine heatwave = thermal stress)

-   We don't know if/how marine microplastic leachate affects the symbiotic relationship between Cnidarian hosts and their algal symbionts

> Why do we care about filling in this knowledge gap? Why *should* we fuck around and find out?

### Questions

#### Overarching

-   How do the combined stressors of [marine microplastic leachate]{.underline} and [thermal stress]{.underline} affect the physiology of the temperate coastal anemone *Anthopleura elegantissima*?

-   Does [marine microplastic leachate]{.underline} reduce Cnidarians' capacity for resilience to [thermal stress]{.underline}?

#### Microbiome

-   Does exposure to **marine microplastic leachate** disrupt the function of the *A. elegantissima* microbiome community?

-   Does exposure to **thermal stress** disrupt the function of the *A. elegantissima* microbiome community?

-   Is exposure to the combined stressors of **marine microplastic leachate** and **thermal stress**

#### Differential Gene Expression

#### Respiration

#### Photosynthesis

### Hypotheses

-   Symbionts play a critical role in the stress response of Cnidarians to thermal stress

-   Microplastic leachate exposure changes the microbial community

-   Microplastic leachate exposure changes the microbial community in such a way that Cnidarians are more susceptible to thermal stress

-   Microplastic leachate and thermal stress act synergistically to disrupt Cnidarian microbial communities

-   The microbial community changes differently when exposed to microplastic stress as compared to thermal stress

### Statistical analysis

### Sample size

### Experimental design

### Controlling batch effects or confounding variables

## Timeline

#### Schedule detail:

-   05-JAN-2024: submitted scientific collection permit
-   26-FEB-2024: received scientific collection permit
-   06-MAR-2024: SST & KH scouted collection site at Point Defiance
-   08-MAR-2024: Seattle Aquarium seawater pickup

## Equipment

| item        | purpose     | location             | status  |
|-------------|-------------|----------------------|---------|
| 2 seatables | water baths | portage bay building | working |
|             |             |                      |         |
|             |             |                      |         |

## Budget

| item                               | quantity | cost | source |
|------------------------------------|----------|------|--------|
| 0.5 pint Kerr Wide Mouth Mason Jar | 60       |      |        |
|                                    |          |      |        |
|                                    |          |      |        |

## Permits

Washington Department of Fish & Wildlife scientific collection permit (Tanja 24-010) was submitted on 05-JAN-2024 and the \$117 processing fee was paid from the lab's purchase card over the phone on 08-JAN-2024. WDFW scientific collection permits can take up to 3 months to be approved. The final permit was approved on 26-FEB-2024. The permit allows for 40 lethal-take and 40 non-lethal take anemones to be collected at each of the following sites: - Keystone Jetty, Island County - Pocket Beach, King County - Skyline Wall, Skagit County - Deadman Bay, San Juan County - Sunrise Beach Park, Pierce County - Chuckanut Bay, Whatcom County - Cone Island, Skagit County - Point Defiance Park, Pierce County - Constellation Park, King County

## Data & Code Organization
